name: Delete Contentful Branch Environment
description: Delete Contentful Branch Environment as part of CI
author: 'Oleksandr Makarenko'
runs:
  using: node16
  main: dist/index.js

inputs:
  environment_name_prefix:
    description: Prefix added to branch name that is used to delete contentful environment

outputs:
  environment_name:
    description: The name of the Contentful environment deleted
